import os
from dotenv import load_dotenv
import rag_retrival
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

def load_model(model_name: str, device:str= None) -> tuple[AutoTokenizer, AutoModelForCausalLM]:
    """Loads a language model and its tokenizer from Hugging Face."""
    
    print(f"Loading model: {model_name} ...")

    if device is None:
        if torch.cuda.is_available():
            resolved_device = "cuda"
        elif torch.backends.mps.is_available():
            resolved_device = "mps"
        else:
            resolved_device = "cpu"
    else:
        resolved_device = str(device).strip().lower()
        aliases = {
            "gpu": "cuda",
            "cuda": "cuda",
            "cpu": "cpu",
            "mps": "mps",
        }
        if resolved_device not in aliases:
            raise ValueError("device must be one of: CPU, CUDA/GPU, MPS")
        resolved_device = aliases[resolved_device]

    tok = AutoTokenizer.from_pretrained(model_name, use_fast=True)

    model_kwargs = {"torch_dtype": "auto"}
    if resolved_device == "cuda":
        model_kwargs["device_map"] = "auto"

    model = AutoModelForCausalLM.from_pretrained(model_name, **model_kwargs)

    if resolved_device != "cuda":
        model = model.to(torch.device(resolved_device))

    dtype = next(model.parameters()).dtype
    model.eval()

    print(f"Model loaded on {resolved_device.upper()} (dtype={dtype})")
    return tok, model

# tok, model = load_model()

def summarize_reviews(docs: str, tok: AutoTokenizer, model: AutoModelForCausalLM) -> str:
    
    system_prompt = f"""You are a helpful assistant for summarizing Yelp reviews. Your task is to analyze the provided reviews and generate concise summaries that capture the key themes, sentiments, and representative quotes from the reviews. Focus on providing aoverall sentiment while ensuring that your summaries are grounded in the actual content of the reviews.

    Here are the reviews you must summarize:
    {docs}

    When summarizing, consider the following aspects:
    1) Top praised themes: Identify common positive aspects mentioned across the reviews (e.g., great service, delicious food, cozy atmosphere).
    2) Top complaints: Highlight recurring negative themes (e.g., long wait times, poor customer service, high prices).
    3) Sentiment: Determine the overall sentiment of the reviews (positive, mixed, or negative).
    4) Representative quotes: Select 3 short quotes from the reviews that exemplify the overall sentiment and key themes.
    5) Confidence: Assess the confidence level of your summary based on the consistency and clarity of the reviews (low, medium, high).
    
    You must format your summary in a clear and structured manner, ensuring that it is concise and directly reflects the content of the reviews. Avoid making assumptions or adding information that is not present in the reviews. Your goal is to provide an accurate and insightful summary that can help business owners understand their customers' experiences and identify areas for improvement.
    """

    conversation = (
    f"<|system|>\n{system_prompt}\n"
    f"<|assistant|>\n")
    
    inputs = tok(conversation, return_tensors="pt")
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=700,
            do_sample=True,
            temperature=0.5,
            top_p=0.9,
            eos_token_id=tok.eos_token_id,
        )
        # Decode only the new tokens generated by the model
        response = tok.decode(outputs[0, inputs["input_ids"].shape[1]:], skip_special_tokens=True).strip()
    return response


if __name__ == "__main__":

    MODEL_NAME = "Qwen/Qwen3-0.6B"
    print("=====Loading vectorstore...=====")
    rag = rag_retrival.load_vectorstore()
    print("=====Vectorstore loaded.=====")

    print("=====Retrieving reviews...=====")
    metadata_filter = {
        "categories": "Italian",
        'business_name': None,
        "city": None,
        "state": None,
        "review_stars": None
    }
    docs = rag_retrival.retrieve_reviews_for_summary(rag, metadata_filter=metadata_filter, k=10)
    print("=====Reviews retrieved.=====")

    if torch.backends.mps.is_available():
        device = "MPS"
        print("Running on Apple Silicon GPU (MPS)")
    elif torch.cuda.is_available():
        device = "CUDA"
        print("Running on NVIDIA GPU (CUDA)")
    else:
        device = "CPU"
        print("Running on CPU")

    print("=====Loading language model...=====")
    tok, model = load_model(MODEL_NAME, device=device)

    print("=====Generating summary...=====")
    summary = summarize_reviews(docs, tok, model)
    print("=====Summary generated.=====\n")
    print("=====BUSINESS SUMMARY=====")
    print(summary)
